name: 10th District Scraper

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install axios

      - name: Run scraper
        run: node "BSEB 10TH RESULT/Bseb 10th Result 2026/script.js"

      - name: Commit safely
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "bot@github.com"

          git add .

          git commit -m "Update district data" || echo "No changes"

          git pull --rebase --autostash origin main

          git push
