name: BSEB Valid Roll Code Finder

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium

      - name: Run Script
        run: node script.js

      - name: Upload Result Files
        uses: actions/upload-artifact@v4
        with:
          name: bseb-valid-roll-codes
          path: |
            bseb-12th-college-list-2026.json
            progress.txt
